using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTech.LinkGuard.Editor.ProGuard
{
    internal static class ProGuardRulesBuilder
    {
        public const string Header = "# Generated by Link Guard. Do not edit by hand.";

        private static readonly AndroidArtifactSource[] GroupOrder =
        {
            AndroidArtifactSource.Aar,
            AndroidArtifactSource.AndroidLib,
            AndroidArtifactSource.Jar,
            AndroidArtifactSource.JavaSource,
        };

        public static string Build(IReadOnlyList<AndroidArtifactEntry> entries)
        {
            Dictionary<AndroidArtifactSource, List<string>> bySource =
                new Dictionary<AndroidArtifactSource, List<string>>();
            HashSet<string> seen = new HashSet<string>(StringComparer.Ordinal);

            if (entries != null)
            {
                foreach (AndroidArtifactEntry entry in entries)
                {
                    foreach (string rule in BuildRulesForEntry(entry))
                    {
                        if (!seen.Add(rule))
                        {
                            continue;
                        }

                        if (!bySource.TryGetValue(entry.Source, out List<string> bucket))
                        {
                            bucket = new List<string>();
                            bySource[entry.Source] = bucket;
                        }

                        bucket.Add(rule);
                    }
                }
            }

            StringBuilder builder = new StringBuilder();
            builder.Append(Header).Append('\n');

            foreach (AndroidArtifactSource source in GroupOrder)
            {
                if (!bySource.TryGetValue(source, out List<string> rules) || rules.Count == 0)
                {
                    continue;
                }

                builder.Append('\n');
                builder.Append("# ").Append(GetGroupComment(source)).Append('\n');

                foreach (string rule in rules.OrderBy(r => r, StringComparer.Ordinal))
                {
                    builder.Append(rule).Append('\n');
                }
            }

            return builder.ToString();
        }

        private static IEnumerable<string> BuildRulesForEntry(AndroidArtifactEntry entry)
        {
            if (entry == null || !entry.ProducesEntry)
            {
                yield break;
            }

            if (entry.IsArtifactSelected)
            {
                IEnumerable<string> nonEmptyPackages = entry.Packages
                    .Select(p => p.Fullname)
                    .Where(p => !string.IsNullOrEmpty(p));

                foreach (string root in CollapseToRoots(nonEmptyPackages))
                {
                    yield return PackageRule(root);
                }

                foreach (JavaClassEntry defaultPackageClass in entry.Classes.Where(c => string.IsNullOrEmpty(c.Package)))
                {
                    foreach (string rule in ClassRules(defaultPackageClass))
                    {
                        yield return rule;
                    }
                }

                yield break;
            }

            foreach (JavaPackageEntry package in entry.Packages)
            {
                if (!package.ProducesEntry)
                {
                    continue;
                }

                if (package.IsSelected && package.Classes.Count > 1 && !string.IsNullOrEmpty(package.Fullname))
                {
                    yield return PackageRule(package.Fullname);
                    continue;
                }

                foreach (JavaClassEntry javaClass in package.Classes.Where(c => c.IsSelected))
                {
                    foreach (string rule in ClassRules(javaClass))
                    {
                        yield return rule;
                    }
                }
            }
        }

        private static IEnumerable<string> ClassRules(JavaClassEntry javaClass)
        {
            yield return $"-keep class {javaClass.Fullname} {{ *; }}";

            if (javaClass.HasInnerClasses)
            {
                yield return $"-keep class {javaClass.Fullname}$** {{ *; }}";
            }
        }

        private static string PackageRule(string package)
        {
            return $"-keep class {package}.** {{ *; }}";
        }

        public static IReadOnlyList<string> CollapseToRoots(IEnumerable<string> packages)
        {
            List<string> distinct = packages
                .Where(p => !string.IsNullOrEmpty(p))
                .Distinct(StringComparer.Ordinal)
                .ToList();

            List<string> roots = new List<string>();

            foreach (string candidate in distinct)
            {
                bool covered = distinct.Any(other =>
                    !string.Equals(other, candidate, StringComparison.Ordinal)
                    && candidate.StartsWith(other + ".", StringComparison.Ordinal));

                if (!covered)
                {
                    roots.Add(candidate);
                }
            }

            return roots;
        }

        private static string GetGroupComment(AndroidArtifactSource source)
        {
            return source switch
            {
                AndroidArtifactSource.Aar => "AAR plugins",
                AndroidArtifactSource.AndroidLib => "Android libraries",
                AndroidArtifactSource.Jar => "JAR plugins",
                AndroidArtifactSource.JavaSource => "Java/Kotlin sources",
                _ => "Android artifacts"
            };
        }
    }
}
